### ISSUE TITLE
Incomplete User Attribute Set Returned?

### ISSUE THREAD

**Issue by ikbarnett** [dthree/addict#25]
Trying to return some user attributes (pager, mobile) via /user but they never appear even though the user I'm searching for has values populated for both. When I try to dump the entire user object, quite a few attribute:value pairs are not returned. 

However, I can find the user by searching for these same attributes using /find

For example, 

/find/pager=_1234567890_

Returns the correct user. So I know I can correctly access the user object in AD

Suggestions?

**Comment by fei0x** [comment]
I needed to change the format that the groups were returned in, so I dug around and can tell you where you can change the content of the responses.

What's returned is managed by a dependency a couple layers deep.
Open and edit this file:
https://github.com/gheeres/node-activedirectory/blob/master/lib/activedirectory.js
I found it here in my local ubuntu:
/usr/local/lib/node_modules/addict/node_modules/activedirectory/lib/activedirectory.js

then look for the following code:

var defaultAttributes, originalDefaultAttributes;
defaultAttributes = originalDefaultAttributes = {
  user: [ 
    'dn',
    'userPrincipalName', 'sAMAccountName', /*'objectSID',*/ 'mail',
    'lockoutTime', 'whenCreated', 'pwdLastSet', 'userAccountControl',
    'employeeID', 'sn', 'givenName', 'initials', 'cn', 'displayName',
    'comment', 'description' 
  ],
  group: [
    'dn', 'cn', 'description'
  ]
};

you can change this block to alter what is returned when you get a user or group.
For example I added member and memberOf to users and groups:

var defaultAttributes, originalDefaultAttributes;
defaultAttributes = originalDefaultAttributes = {
  user: [ 
    'dn',
    'userPrincipalName', 'sAMAccountName', /*'objectSID',*/ 'mail',
    'lockoutTime', 'whenCreated', 'pwdLastSet', 'userAccountControl',
    'employeeID', 'sn', 'givenName', 'initials', 'cn', 'displayName',
    'comment', 'description', 'memberOf' 
  ],
  group: [
    'dn', 'cn', 'description','member','memberOf'
  ]
};

**Comment by ikbarnett** [comment]
Perfect. Thanks! I was going down this path but you beat me to it. Added the specific attributes I was needing to the default user list as you said in activedirectory.js and it worked.

**Comment by fei0x** [comment]
Yeah, not being too familiar with this sort of Javascript it took me quite some time to find the spot. Glad to save somebody else the pain. ^^d

**Comment by ilyaglow** [comment]
Unfortunately, `addict` isn't depending on `activedirectory` package now :(
