### ISSUE TITLE
specify port other than 80?

### ISSUE THREAD

**Issue by jamenlang** [dthree/addict#6]
I haven't had a chance to look through the code, and I know very little about nodejs, is there a config.json option for the port that i can hit /api on? both 443 and 80 are in use by apache.

**Comment by dthree** [comment]
Yes. Pass `--port` into the args, or in the config, or as an env variable as `ADDICT_PORT`. I'll update the docs.

**Comment by jamenlang** [comment]
I re-ran the npm install line

npm i addict-api -g
/usr/bin/addict -> /usr/lib/node_modules/addict-api/bin/index.js
/usr/bin/addict-cli -> /usr/lib/node_modules/addict-api/bin/index.js
+ addict-api@0.1.6
updated 1 package in 2.929s

port is not an option, addict --url redacted --user redacted@redacted --pass superredacted --port 895

Invalid option: 'port'. Showing Help:

**Comment by dthree** [comment]
Okay. It looks like I hadn't pushed my latest fixes. I have also adjusted the npm package from `addict-api` to just `addict` (was working with npm to get that name freed up).



So try again now with `addict`, latest version is `1.0.5`.

**Comment by jamenlang** [comment]
+ addict@1.0.5
added 125 packages in 8.291s

addict --url redacted --user redacted@redacted --pass superredacted --port 895

Invalid option: 'port'. Showing Help:

**Comment by dthree** [comment]
Err, I just tried it on a totally fresh setup and it was fine:

`addict --user xxx@xxxxx.net --pass xxx --url ldaps://xxx --port 3100`

Try `npm uninstall -g addict`

then

`npm install -g addict`

**Comment by jamenlang** [comment]
i had both addict and addict-cli in /usr/local/bin, after uninstalling them with npm uninstall i was still able to run addict from cli. 

I removed both addict and addict-cli from /usr/local/bin, npm install -g addict does not put either back...

**Comment by dthree** [comment]
That's really odd--do you have a fresh image you can try from, maybe a docker repo?

It might be some permissions problem in /usr/local/bin after deleting? It's more of an npm question.

**Comment by jamenlang** [comment]
I uninstalled node and npm, ran apt-get clean, reinstalled node, re-ran npm i -g addict, I see that it changed directories, it's at /usr/bin/ now. 

It rebuilt the link and it runs fine now. except for #8

**Comment by dthree** [comment]
Good!
