### ISSUE TITLE
is there a log file that i can check for errors?

### ISSUE THREAD

**Issue by jamenlang** [dthree/addict#8]
I can get to the /api page but the logo is a broken link and all api commands that i run give me 503 service unavailable.

What can I provide for logs?

"lde_message": "0000202B: RefErr: DSID-0310082F, data 0, 1 access points\n\tref 1: 'redacteddomain'\n\u0000",
  "lde_dn": null,
  "error": true
}

**Comment by jamenlang** [comment]
FIXED - I see that the --user flag needs quotes around it, I'm guessing it doesn't like the period in the domain

**Comment by dthree** [comment]
Okay, great!

**Comment by jared-christensen** [comment]
I'm having the same issue but using quotes did not fix it.
```javascript
{
"lde_message": "0000202B: RefErr: DSID-0310082F, data 0, 1 access points\n\tref 1: 'earthweb'\n\u0000",
  "lde_dn": null,
  "error": true
}
```

**Comment by jaypark96** [comment]
Same.
